application: improve-facebookapp-test
version: 2
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /js
  static_dir: js  
- url: /.*
  script: main.app
